### ISSUE TITLE
Single period picker doesn't apply selected period

### ISSUE THREAD

**Issue by spanitz** [gfke/yoso-datepicker#1]
If a preselected period is applied, i'm unable to edit this period. In addition, the Directive should behave differently if just a single period is allowed. Selecting for editing shouldn't be necessary and it also should prevent deletion.

Markup:
```html
    <yoso-date-picker
        class="yoso-datepicker"
        ...
        start-date="2014-01-01"
        end-date="2015-02-01"
        preselected-periods="[{periodMode:'w',start:'2015-01-01',end:'2015-02-01'}]"
        max-selectable-periods="1">
    </yoso-date-picker>
```

**Comment by lukas-zech-software** [comment]
Fixed in v0.4.0
